### ISSUE TITLE
[3pt]  - Add all items counter on the Homepage - Student A

### ISSUE THREAD

**Issue by mrjuda** [mrjuda/capstone1#8]
Even if the API gives you the number of items, you will create a specific function to calculate it.

Make sure that the correct number is displayed on the Homepgae.

**Comment by Have-Samuel** [comment]
Add all items counter on the Homepage

![image](https://user-images.githubusercontent.com/83591312/163594999-a17a9eaa-2033-42d1-a8ce-efe6ab302055.png)
Even if the API gives you the number of items, you will create a specific function to calculate it.

Make sure that the correct number is displayed on the Homepgae.
